apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: /workspace/Dockerfile

  steps:
  - name: build-and-push
    # Newer versions of kaniko expect credentials outside of ~/.docker/config
    # Pin to v0.1.0 until
    # https://github.com/GoogleContainerTools/kaniko/issues/392 is resolved
    image: gcr.io/kaniko-project/executor:v0.1.0
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
